---
- hosts: all
  
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: johvna2025
    group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: Check the time 
      command: dateskls
#      when: ansible_distribution == "johvna" or ansible_processor_nproc == 2
    - name: create user johana
      user:
         name: "{{user_name}}"
         comment: Johana Admin
    - name: create group
      group: 
         name: "{{group_name}}"
         state: present
      become: true   
    - name: Install package
      package:
         name: "{{pkg_name}}"
         state: present     